// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPwIdVrBrGnzOAHvG61di9RBK4LKHuAfo',
    appId: '1:379123032105:web:363f42ca0ef8ed7a6e3c38',
    messagingSenderId: '379123032105',
    projectId: 'flutter-register-e5ed8',
    authDomain: 'flutter-register-e5ed8.firebaseapp.com',
    storageBucket: 'flutter-register-e5ed8.firebasestorage.app',
    measurementId: 'G-XR5EDN5EEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTANURqjgiF3ebUfznFIk33WmGrdLo3mE',
    appId: '1:379123032105:android:23cd2995124341446e3c38',
    messagingSenderId: '379123032105',
    projectId: 'flutter-register-e5ed8',
    storageBucket: 'flutter-register-e5ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIx67UlK-JqM4qoASCb5I5TcyHPkOUquc',
    appId: '1:379123032105:ios:1867a568770287ff6e3c38',
    messagingSenderId: '379123032105',
    projectId: 'flutter-register-e5ed8',
    storageBucket: 'flutter-register-e5ed8.firebasestorage.app',
    iosBundleId: 'com.example.day3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIx67UlK-JqM4qoASCb5I5TcyHPkOUquc',
    appId: '1:379123032105:ios:1867a568770287ff6e3c38',
    messagingSenderId: '379123032105',
    projectId: 'flutter-register-e5ed8',
    storageBucket: 'flutter-register-e5ed8.firebasestorage.app',
    iosBundleId: 'com.example.day3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPwIdVrBrGnzOAHvG61di9RBK4LKHuAfo',
    appId: '1:379123032105:web:b26b1e15dc4b9e416e3c38',
    messagingSenderId: '379123032105',
    projectId: 'flutter-register-e5ed8',
    authDomain: 'flutter-register-e5ed8.firebaseapp.com',
    storageBucket: 'flutter-register-e5ed8.firebasestorage.app',
    measurementId: 'G-TBTRW4JKWE',
  );
}
